### ISSUE TITLE
Enable touch-sensitive keyboard scrolling on Passport

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/safe-browse#49]
```
ListView:
scrollRole: ScrollRole.Main
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 15 Jan 2015 at 9:54

**Comment by canadainc** [comment]
1353bdc4b057e90178d02af120092a79cb1f97b7

**Comment by canadainc** [comment]
Verified on R135, GCR v2.3.0.0
